In [33]:
# develop a ar model 
from statsmodels.tsa.ar_model import AutoReg
from statsmodels.tsa.arima.model import ARIMA
import pandas as pd
# invalid import
import yfinance as yf

In [34]:
df = pd.read_csv(r"C:\Users\Terrence Poon\Desktop\pyTrading\data\0700.HK.csv")
df = df.dropna()

In [35]:
model = AutoReg(df['Close'], lags = 2)
model_fit = model.fit()
print(model_fit.params)

# 700_tmr Price = 0.1609 + 1.004574 * 700_today + -0.005109 * 700_yesterday
# const = intercept; Lag(1) = coefficient; Lag(2) = coefficient

const       0.160962
Close.L1    1.004574
Close.L2   -0.005109
dtype: float64


D:\Anaconda\lib\site-packages\statsmodels\tsa\base\tsa_model.py:471: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)


In [44]:
close_prices = df['Close']
train, test = close_prices[:-1], 384.34
model = ARIMA(train, order = (5,2,3))
results = model.fit()
forecast = results.forecast()
predicted = forecast[0]
print(f'Predicted price on {to_date}: {round(predicted, 2)}$')
# print(f'Actual price on {to_date}: {round(test, 2)}$')


D:\Anaconda\lib\site-packages\statsmodels\tsa\base\tsa_model.py:471: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
D:\Anaconda\lib\site-packages\statsmodels\tsa\base\tsa_model.py:471: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
D:\Anaconda\lib\site-packages\statsmodels\tsa\base\tsa_model.py:471: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)
D:\Anaconda\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
D:\Anaconda\lib\site-packages\statsmodels\tsa\base\tsa_model.py:834: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.
  return get_predic

KeyError: 0

In [82]:
import torch
#f(x1, x2, x3, x4) = x_1^3 * x_2 + x_3 * x_4
def get_function(x1_val = 0, x2_val = 0, x3_val = 0, x4_val = 0):
# variables; requires_grad = need derivative?
    x1 = torch.tensor(x1_val, requires_grad = True, dtype = torch.float32)
#     print(x1)
    x2 = torch.tensor(x2_val, requires_grad = True, dtype = torch.float32)
#     print(x2)
    x3 = torch.tensor(x3_val, requires_grad = True, dtype = torch.float32)
#     print(x3)
    x4 = torch.tensor(x4_val, requires_grad = True, dtype = torch.float32)
#     print(x4)
    # function
    p1 = x1.pow(3)
#     print(p1)  # PowBackward()
    m1 = p1 * x2
#     print(m1)  # MullBackward()
    m2 = x3 * x4
#     print(m2)  # MullBackward()
    f = m1 + m2
#     print(f)   # AddBackward()
    vars = {'x1': x1, 'x2': x2, 'x3': x3, 'x4': x4}

    return f, vars

In [83]:
abc, cd = get_function(2,4,3,5)

In [84]:
abc.item()

47.0

In [66]:
cd

{'x1': tensor(2., requires_grad=True),
 'x2': tensor(4., requires_grad=True),
 'x3': tensor(3., requires_grad=True),
 'x4': tensor(5., requires_grad=True)}

In [89]:
# show first derivative
from torch.autograd import grad

f, params = get_function(2,4,3,5)
# df_dx1 = grad(outputs=f, inputs = [params['x4']])  # x1 d first variable
df_dx = grad(outputs=f, inputs = params.values()) # d all variables
print(f)
print(type(f))
print(df_dx)
# print(df_dx1)

tensor(47., grad_fn=<AddBackward0>)
<class 'torch.Tensor'>
(tensor(48.), tensor(8.), tensor(5.), tensor(3.))


In [88]:
x = torch.tensor(data = [[1,2,3],[4,5,6]], dtype=torch.float32, requires_grad=True)

In [86]:
# Ones / twos / eye 

# tmp = grad(outputs=, inputs=x)

TypeError: 'int' object is not iterable

In [1]:
import torch
import random

# set 2 x 2 dimensions with all zeros values
x = torch.zeros((2, 2))
print(x)

# set 2 x 2 dimensions with all one values
x = torch.ones((2, 2))
print(x)

# set 2 x 2 dimensions with identical tensor
x = torch.eye(3)
print(x)

# Reshape 
y = x.reshape((2, 2)) # [1, 2, 3, 4] [[1, 2],[3, 4]]

# Size 
x.size() # [2, 3]

# Dim 
x.dim() # 2 

# Tolist - tensor values
x.tolist()

# Cal Gradient 
x = torch.tensor(data = [2], dtype=torch.float32, requires_grad=True)
f = x.pow(2)
f.backward() # why backward? 
x.grad.item()

# abs - absolute value
# add - add a scaler
# ceil - return a new tensor greater than or equal to each element of a tensor 
# dist 
# div - divides each element 
# eq - element-wise equality
# floor - return a new tensor greater than or less each element of a tensor 
# mean - mean value  
# pow 
# max - max value
# min - min value 
# round  # sign  # sum

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


RuntimeError: shape '[2, 2]' is invalid for input of size 9

In [3]:
import torch
#f(x1, x2, x3, x4) = x_1^3 * x_2 + x_3 * x_4
def get_hypofunction(x1_val = 0, x2_val = 0, x3_val = 0, x4_val = 0, x5_val = 0):
# variables; requires_grad = need derivative?
    x1 = torch.tensor(x1_val, requires_grad = True, dtype = torch.float32)
#     print(x1)
    x2 = torch.tensor(x2_val, requires_grad = True, dtype = torch.float32)
#     print(x2)
    x3 = torch.tensor(x3_val, requires_grad = True, dtype = torch.float32)
#     print(x3)
    x4 = torch.tensor(x4_val, requires_grad = True, dtype = torch.float32)
    x5 = torch.tensor(x5_val, requires_grad = True, dtype = torch.float32)
#     print(x4)
    # function
    p1 = x1.pow(3)
#     print(p1)  # PowBackward()
    m1 = p1 * x2
    m3 = m1 / x5
    print(m3)
#     print(m1)  # MullBackward()
    m2 = x3 * x4
#     print(m2)  # MullBackward()
    f = m1 + m2
#     print(f)   # AddBackward()
    vars = {'x1': x1, 'x2': x2, 'x3': x3, 'x4': x4}

    return f, vars

In [4]:
abc = get_hypofunction(2,4,5,6,7)

tensor(4.5714, grad_fn=<DivBackward0>)


In [5]:
abc

(tensor(62., grad_fn=<AddBackward0>),
 {'x1': tensor(2., requires_grad=True),
  'x2': tensor(4., requires_grad=True),
  'x3': tensor(5., requires_grad=True),
  'x4': tensor(6., requires_grad=True)})

In [9]:
ll = torch.nn.Linear(3,2) # 3 elements 2 layers
print(ll.weight) # initialize with random weights and biases

Parameter containing:
tensor([[-0.5439, -0.3075,  0.1234],
        [-0.0592,  0.4512, -0.1335]], requires_grad=True)
